name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: praveensirvi/python-flask-hello-world:latest
    
    - name: Deploy to Kubernetes
      uses: docker://nickgronow/kubectl:1.17
      with:
        args: create deployment hello-world --image=praveensirvi/python-flask-hello-world:latest
        config_data: ${{ secrets.KUBECONFIG }}

    - name: Verify deployment
      uses: nickgronow/kubectl@master
      with:
        config_data: ${{ secrets.KUBECONFIG }}
        args: '"rollout status deployment/<my-deploy>"'
    
