name: Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: praveensirvi/python-flask-hello-world:latest
    
    - name: Set up Kubernetes environment
      uses: engineerd/setup-kubectl@v1.0.1
      with:
          kubeconfig: |
            apiVersion: v1
            kind: Config
            clusters:
            - name: minikube
              cluster:
                server: https://192.168.49.2:8443
                certificate-authority: /home/praveen/.minikube/ca.crt
            contexts:
            - name: minikube
              context:
                cluster: minikube
                user: minikube
            current-context: minikube
            users:
            - name: minikube
              user:
                client-certificate: /home/praveen/.minikube/profiles/minikube/client.crt
                client-key: /home/praveen/.minikube/profiles/minikube/client.key
    - name: Deploy app
      run: |
        kubectl apply -f deployment.yaml 
